config/routes.rb
ControlLaboratorio::Application.routes.draw do

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "registro" => "users#new", :as => "registro"

  resources :users

  resources :sessions

  resources :productos

  resources :proveedores

  resources :pastas do
    member do
      get :estadisticas
    end
  end

  resources :pruebas
  resources :hornos do
    resources :mediciones
  end

  root :to => "sessions#new"

end

app/models/producto.rb
class Producto < ActiveRecord::Base
  has_many :composiciones
  belongs_to :proveedor
  attr_accessible :proveedor_id, :referencia, :caracteristica
  validates_presence_of :proveedor_id, :referencia, :caracteristica
end

# == Schema Information
#
# Table name: productos
#
#  id             :integer         not null, primary key
#  proveedor_id   :integer
#  referencia     :string(255)
#  caracteristica :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_filter :establecer_tab
  def index
    @productos = Producto.all
  end

  def show
    @producto = Producto.find(params[:id])
  end

  def new
    @producto = Producto.new
  end

  def create
    @producto = Producto.new(params[:producto])
    if @producto.save
      redirect_to @producto, :notice => "Successfully created producto."
    else
      render :action => 'new'
    end
  end

  def edit
    @producto = Producto.find(params[:id])
  end

  def update
    @producto = Producto.find(params[:id])
    if @producto.update_attributes(params[:producto])
      redirect_to @producto, :notice  => "Successfully updated producto."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy
    redirect_to productos_url, :notice => "Successfully destroyed producto."
  end
  private
  def establecer_tab
    @tab = "Productos"
  end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.haml
= form_for @producto do |f|
  = f.error_messages
  %ol
    %li
      = f.label :proveedor_id
      = select("producto", "proveedor_id", Proveedor.all.collect {|p| [p.nombre, p.id]}, {:prompt => '--proveedores--'})
    %li
      = f.label :referencia
      = f.text_field :referencia
    %li
      = f.label :caracteristica
      = f.text_field :caracteristica
    %li
      = f.submit

app/views/productos/edit.html.haml
- title "Modificación de productos"

= render 'form'

#enlacebotton
  %p
    = link_to "Productos", productos_path

app/views/productos/index.html.haml
- title "Productos"

%table
  %tr
    %th Proveedor
    %th Referencia
    %th Caracteristica
  - for producto in @productos
    %tr
      %td= producto.proveedor.nombre
      %td= link_to producto.referencia, producto
      %td= producto.caracteristica
      %td.enlacebotton= link_to 'Modificar', edit_producto_path(producto)
#enlacebotton
  %p= link_to "Nuevo producto", new_producto_path

app/views/productos/new.html.haml
- title "Nuevo Producto"

= render 'form'

#enlacebotton
  %p= link_to "Vista productos", productos_path

app/views/productos/show.html.haml
- title "Producto #{@producto.referencia}"

%p
  %strong Proveedor:
  = @producto.proveedor.nombre
%p
  %strong Referencia:
  = @producto.referencia
%p
  %strong Caracteristica:
  = @producto.caracteristica

#enlacebotton
  %p
    = link_to "Eliminar", @producto, :confirm => '¿Estas seguro? Esta acción no se podra deshacer.', :method => :delete
    = link_to "Productos", productos_path