config/routes.rb
ControlLaboratorio::Application.routes.draw do

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "registro" => "users#new", :as => "registro"

  resources :users

  resources :sessions

  resources :productos

  resources :proveedores

  resources :pastas do
    member do
      get :estadisticas
    end
  end

  resources :pruebas
  resources :hornos do
    resources :mediciones
  end

  root :to => "sessions#new"

end

app/models/prueba.rb
class Prueba < ActiveRecord::Base
  belongs_to :pasta
  belongs_to :horno
  has_many :composiciones, :dependent => :destroy
  has_one :control
  attr_accessible :pasta_id, :fecha, :horno_id, :partida, :composiciones_attributes, :control_attributes
  accepts_nested_attributes_for :composiciones, :reject_if => lambda { |a| a[:porcentaje].blank?}, :allow_destroy => true
  accepts_nested_attributes_for :control, :reject_if => lambda { |a| a[:valor_x].blank?}, :allow_destroy => true
  validates_presence_of :pasta_id, :fecha, :partida
end


# == Schema Information
#
# Table name: pruebas
#
#  id         :integer         not null, primary key
#  pasta_id   :integer
#  fecha      :datetime
#  partida    :string(255)
#  created_at :datetime
#  updated_at :datetime
#  horno_id   :integer
#

app/controllers/pruebas_controller.rb
#encoding: utf-8
class PruebasController < ApplicationController
  before_filter :establecer_tab
  skip_before_filter :autorizar

  def index

      @pruebas = Prueba.includes([:pasta, :horno]).order('fecha desc')

  end

  def show
    @prueba = @pasta.nil? ? Prueba.find(params[:id]) : @pasta.pruebas.find(params[:id])
  end

  def new
    @prueba = Prueba.new
    find_productos
  end

  def create
    @prueba = Prueba.new(params[:prueba])
    if @prueba.save
      redirect_to pruebas_path, :notice => "La creación de la prueba se ejuto con exito."
    else
      find_productos
      render :action => 'new'
    end
  end

  def edit
    @prueba = Prueba.find(params[:id])
    if @prueba.control.nil?
      @prueba.build_control
    end
    find_productos
  end

  def update
    @prueba = Prueba.find(params[:id])
    if @prueba.update_attributes(params[:prueba])
      redirect_to pruebas_path, :notice  => "La prueba se ha actualizado."
    else
      find_productos
      render :action => 'edit'
    end
  end

  def destroy
    @prueba = Prueba.find(params[:id])
    @prueba.destroy redirect_to pruebas_url, :notice => "Se han borrado los datos de la prueba"
  end

  private

  def establecer_tab
    @tab = "Pruebas"
  end
  def find_productos
    @productos = Producto.all.collect {|p| [p.referencia, p.id]}
  end

end

app/helpers/pruebas_helper.rb
module PruebasHelper
end

app/views/pruebas/_composicion_fields.html.haml
= composicion_fields.select(:producto_id, @productos , {:prompt => '--productos--'})
=composicion_fields.text_field :porcentaje
=composicion_fields.text_field :comentario

app/views/pruebas/_control_fields.html.haml
%fieldset
  %legend control de la prueba
  %ol
    %li
      =control_fields.label :valor_x
      =control_fields.text_field :valor_x
      %br
    %li
      =control_fields.label :valor_y
      =control_fields.text_field :valor_y
      %br
    %li
      =control_fields.label :valor_z
      =control_fields.text_field :valor_z
      %br

app/views/pruebas/_form.html.haml
= nested_form_for  @prueba do |f|
  = f.error_messages
  #left
    %ol
      %li
        = f.label :pasta_id
        = select("prueba", "pasta_id", Pasta.all.collect {|p| [p.codigo, p.id]}, {:prompt => '--Pasta--'})
      %li
        = f.label :fecha
        = f.datetime_select :fecha
      %li
        = f.label :partida
        = f.text_field :partida
      %li
        = f.label :horno_id
        = select("prueba", "horno_id", Horno.all.collect {|p| [p.codigo, p.id]}, {:prompt => '--Hornos--'})
    #enlacebotton
      %table.nh
        %tr
          %td Producto
          %td Porcentaje
          %td Comentario
      - f.fields_for :composiciones do |composicion_fields|
        =render 'composicion_fields', :composicion_fields => composicion_fields
      %p
        = f.link_to_add "Añade un producto", :composiciones

  #right
    -f.fields_for :control do |control_fields|
      =render 'control_fields', :control_fields => control_fields
  .clear
  %p
    =f.submit

app/views/pruebas/_index.html.haml
- title "Pruebas"
%table
  %tr
    %th Pasta
    %th Fecha
    %th Horno
    %th Partida
  - for prueba in @pruebas
    %tr{:class => cycle("even","odd")}
      %td= prueba.pasta.codigo
      %td= link_to (l prueba.fecha, :format => :long), [@pasta, prueba]
      %td= prueba.horno.try(:codigo)
      %td= prueba.partida
      %td.enlacebotton= link_to 'Modificar', edit_pasta_prueba_path(@pasta, prueba)

#enlacebotton
  %p= link_to "Nueva Prueba", new_pasta_prueba_path(@pasta)

app/views/pruebas/edit.html.haml
- title "Modificar Prueba"

= render 'form'

app/views/pruebas/index.html.haml
- title "Pruebas"
%table
  %tr
    %th Pasta
    %th Fecha
    %th Horno
    %th Partida
  - for prueba in @pruebas
    %tr{:class => cycle("even","odd")}
      %td= prueba.pasta.codigo
      %td= link_to (l prueba.fecha, :format => :long), prueba_path(prueba)
      %td= prueba.horno.try(:codigo)
      %td= prueba.partida
      %td.enlacebotton= link_to 'Modificar', edit_prueba_path(prueba)

#enlacebotton
  %p= link_to "Nueva Prueba", new_prueba_path

app/views/pruebas/new.html.haml
- title "Nueva Prueba"

= render 'form'

app/views/pruebas/show.html.haml
- title "Prueba #{@prueba.pasta.codigo}"
#content_left
  %p
    %strong Pasta:
    = @prueba.pasta_id
  %p
    %strong Fecha:
    = l @prueba.fecha, :format => :long
  %p
    %strong Partida:
    = @prueba.partida
  %p
    %strong Horno:
    = @prueba.horno.try(:codigo)
#content_right
  %table
    %thead
      %tr
        %th Producto
        %th Porcentaje
        %th comentario
    %tbody
      -for composicion in @prueba.composiciones
        %tr
          %td= composicion.producto.referencia
          %td= composicion.porcentaje
          %td= composicion.comentario
  #enlacebotton
    - if @pasta.nil?
      = link_to "Eliminar", @prueba, :confirm => '¿Estas seguro? Esta acción no se podra deshacer.', :method => :delete
      = link_to "Pruebas", pruebas_path
    - else
      = link_to "Pruebas", pasta_pruebas_path(@pasta)
#right
  %table
    %thead
      %tr
        %th{:colspan => 3}
          Control
    %tbody
      %td
        %strong Valor_x:
        = @prueba.control.try(:valor_x)
      %td
        %strong Valor_y:
        = @prueba.control.try(:valor_y)
      %td
        %strong Valor_z:
        = @prueba.control.try(:valor_z)
.clear