config/routes.rb
ControlLaboratorio::Application.routes.draw do

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "registro" => "users#new", :as => "registro"

  resources :users

  resources :sessions

  resources :productos

  resources :proveedores

  resources :pastas do
    member do
      get :estadisticas
    end
  end

  resources :pruebas
  resources :hornos do
    resources :mediciones
  end

  root :to => "sessions#new"

end

app/models/pasta.rb
class Pasta < ActiveRecord::Base
  paginates_per 1
  has_many :pruebas, :dependent => :destroy
  has_many :hornos, :through => :pruebas
  has_many :quemadores, :through => :hornos
  attr_accessible :codigo, :tipo_tierra, :descripcion, :pruebas_attributes, :id
end

# == Schema Information
#
# Table name: pastas
#
#  id          :integer         not null, primary key
#  codigo      :string(255)
#  tipo_tierra :string(255)
#  descripcion :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

app/controllers/pastas_controller.rb
class PastasController < ApplicationController
  before_filter :establecer_tab
  def index
    @pastas = Pasta.all(:include => :pruebas)
  end

  def show
    @pasta = Pasta.find(params[:id])
  end

  def new
    @pasta = Pasta.new
  end

  def create
    @pasta = Pasta.new(params[:pasta])
    if @pasta.save
      redirect_to @pasta, :notice => "Successfully created pasta."
    else
      render :action => 'new'
    end
  end

  def edit
    @pasta = Pasta.find(params[:id])
  end

  def update
    @pasta = Pasta.find(params[:id])
    if @pasta.update_attributes(params[:pasta])
      redirect_to @pasta, :notice  => "Successfully updated pasta."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @pasta = Pasta.find(params[:id])
    @pasta.destroy
    redirect_to pastas_url, :notice => "Successfully destroyed pasta."
  end

  def estadisticas
    @pasta = Pasta.find(params[:id], :include => {:pruebas => [:horno, {:composiciones => :producto}]})
    @pruebas = @pasta.pruebas.order("fecha desc").page(params[:page]).per(1)
  end

  private
  def establecer_tab
    @tab = "Pastas"
  end
end

app/helpers/pastas_helper.rb
module PastasHelper
end

app/views/pastas/_form.html.haml
= form_for @pasta do |f|
  = f.error_messages
  %p
    = f.label :codigo
    %br
    = f.text_field :codigo
  %p
    = f.label :tipo_tierra
    %br
    = f.text_field :tipo_tierra
  %p
    = f.label :descripcion
    %br
    = f.text_field :descripcion
  %p
    = f.submit

app/views/pastas/edit.html.haml
- title "Edit Pasta"

= render 'form'

#enlacebotton
  = link_to "Vista", @pasta
  = link_to "Vista general", pastas_path

app/views/pastas/estadisticas.html.haml
- title "Pasta #{@pasta.codigo}"
#estadistica_left
  -for prueba in @pruebas
    %table.estadistica
      %thead
        %tr
          %th Fecha
          %th Nº Partida
      %tbody
        %tr
          %td= link_to (l prueba.fecha, :format => :long), prueba_path(prueba)
          %td= prueba.partida
    %table.estadistica
      %thead
        %tr
          %th Producto
          %th Porcentaje
          %th comentario
      -for composicion in prueba.composiciones
        %tbody
          %tr
            %td= composicion.producto.referencia
            %td= composicion.porcentaje
            %td= composicion.comentario
    %table.estadistica
      %thead
        %tr
          %th Valor x
          %th Valor y
          %th Valor z
      %tbody
        %tr
          %td= prueba.control.try(:valor_x)
          %td= prueba.control.try(:valor_y)
          %td= prueba.control.try(:valor_z)
    .clear
    %table
      %thead
        %tr
          -prueba.horno.quemadores.each do |quemador|
            %th= quemador.nombre
          -# prueba.horno.mediciones.where("date(fecha) = :fecha", :fecha => prueba.fecha.to_date).each do |medicion|
          - prueba.horno.mediciones.where(:fecha => prueba.fecha.to_date..(prueba.fecha.to_date + 1.day).to_date ).each do |medicion|
            %tr
            - medicion.valores.each do |valor|
              %td
                = valor.temperatura
            %tr
            - medicion.valores.each do |valor|
              %td
                = valor.presion
#paginador
  = paginate @pruebas

app/views/pastas/index.html.haml
- title "Pastas"
%table
  %thead
    %tr
      %th Codigo
      %th Tipo tierra
      %th Descripcion
      %th pruebas
  %tbody
    - for pasta in @pastas
      %tr{:class => cycle("even","odd")}
        %td= link_to pasta.codigo, pasta
        %td= pasta.tipo_tierra
        %td= pasta.descripcion
        %td= "Total #{pasta.pruebas.size}"
        -#%td= link_to "Total #{pasta.pruebas.size}", pasta_pruebas_path(pasta)
        -#%td= link_to 'vista', pasta
        -#%td.enlacebotton= link_to 'nueva prueba', new_pasta_prueba_path(pasta)
        -#%td= link_to 'Pruebas de la pasta', pasta_pruebas_path(pasta)
        -#%td= link_to 'Modificar', edit_pasta_path(pasta)
        -#%td= link_to 'Eliminar', pasta, :confirm => '¿Estas seguro? esta acción no se puede deshacer', :method => :delete
#enlacebotton
  %p= link_to "Nueva Pasta", new_pasta_path

app/views/pastas/new.html.haml
- title "New Pasta"

= render 'form'

#enlacebotton
  = link_to "Vista general", pastas_path

app/views/pastas/show.html.haml
- title "Pasta"
#left
  %p
    %strong Codigo:
    = @pasta.codigo
  %p
    %strong Tipo Tierra:
    = @pasta.tipo_tierra
  %p
    %strong Descripcion:
    = @pasta.descripcion

  #enlacebotton
    = link_to "Modificar", edit_pasta_path(@pasta)
    = link_to "Eliminar", @pasta, :confirm => '¿Estas seguro? Esta acción no se puede deshacer', :method => :delete
    = link_to "Vista general", pastas_path
  #estadistica
    = link_to "Estadisticas", estadisticas_pasta_path
#right
  %table
    %thead
      %tr
        %th Fecha
        %th Nº Partida
    %tbody
      -for prueba in @pasta.pruebas.order('fecha desc')
        %tr
          %td= link_to (l prueba.fecha, :format => :long), prueba_path(prueba)
          %td= prueba.partida
.clear