config/routes.rb
ControlLaboratorio::Application.routes.draw do

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "registro" => "users#new", :as => "registro"

  resources :users

  resources :sessions

  resources :productos

  resources :proveedores

  resources :pastas do
    member do
      get :estadisticas
    end
  end

  resources :pruebas
  resources :hornos do
    resources :mediciones
  end

  root :to => "sessions#new"

end

app/models/composicion.rb
class Composicion < ActiveRecord::Base
  belongs_to :producto
  belongs_to :prueba
  attr_accessible :prueba_id, :producto_id, :porcentaje, :comentario
end

# == Schema Information
#
# Table name: composiciones
#
#  id          :integer         not null, primary key
#  prueba_id   :integer
#  producto_id :integer
#  porcentaje  :integer
#  comentario  :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

app/models/control.rb
class Control < ActiveRecord::Base
  belongs_to :prueba
  attr_accessible :valor_x, :valor_y, :valor_z
  validates_presence_of :prueba_id, :valor_x, :valor_y, :valor_z
end

# == Schema Information
#
# Table name: controles
#
#  id         :integer         not null, primary key
#  prueba_id  :integer
#  valor_x    :integer
#  valor_y    :integer
#  valor_z    :integer
#  created_at :datetime
#  updated_at :datetime
#

app/models/horno.rb
class Horno < ActiveRecord::Base
  attr_accessible :codigo, :longitud, :descripcion, :quemadores_attributes
  has_many :quemadores, :dependent => :destroy
  has_many :mediciones
  has_many :pruebas
  accepts_nested_attributes_for :quemadores,
    :reject_if => lambda { |a| a[:nombre].blank? }, :allow_destroy => true
end

# == Schema Information
#
# Table name: hornos
#
#  id          :integer         not null, primary key
#  codigo      :string(255)
#  longitud    :string(255)
#  descripcion :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

app/models/medicion.rb
class Medicion < ActiveRecord::Base
  belongs_to :horno
  has_many :valores, :dependent => :destroy
  attr_accessible :horno_id, :fecha, :operario, :velocidad_horno, :valores_attributes
  accepts_nested_attributes_for :valores,
    :reject_if => lambda { |a| a[:quemador_id].blank? }, :allow_destroy => true
end

# == Schema Information
#
# Table name: mediciones
#
#  id              :integer         not null, primary key
#  horno_id        :integer
#  fecha           :datetime
#  operario        :string(255)
#  velocidad_horno :integer
#  created_at      :datetime
#  updated_at      :datetime
#

app/models/pasta.rb
class Pasta < ActiveRecord::Base
  paginates_per 1
  has_many :pruebas, :dependent => :destroy
  has_many :hornos, :through => :pruebas
  has_many :quemadores, :through => :hornos
  attr_accessible :codigo, :tipo_tierra, :descripcion, :pruebas_attributes, :id
end

# == Schema Information
#
# Table name: pastas
#
#  id          :integer         not null, primary key
#  codigo      :string(255)
#  tipo_tierra :string(255)
#  descripcion :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

app/models/producto.rb
class Producto < ActiveRecord::Base
  has_many :composiciones
  belongs_to :proveedor
  attr_accessible :proveedor_id, :referencia, :caracteristica
  validates_presence_of :proveedor_id, :referencia, :caracteristica
end

# == Schema Information
#
# Table name: productos
#
#  id             :integer         not null, primary key
#  proveedor_id   :integer
#  referencia     :string(255)
#  caracteristica :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#

app/models/proveedor.rb
class Proveedor < ActiveRecord::Base
  has_many :productos
  attr_accessible :codigo_proveedor, :telefono, :direccion, :contacto, :nombre, :cif
  validates_presence_of :codigo_proveedor, :telefono, :direccion, :nombre, :cif
end



# == Schema Information
#
# Table name: proveedores
#
#  id               :integer         not null, primary key
#  codigo_proveedor :string(255)
#  telefono         :string(255)
#  direccion        :string(255)
#  contacto         :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#  nombre           :string(255)
#  cif              :string(255)
#

app/models/prueba.rb
class Prueba < ActiveRecord::Base
  belongs_to :pasta
  belongs_to :horno
  has_many :composiciones, :dependent => :destroy
  has_one :control
  attr_accessible :pasta_id, :fecha, :horno_id, :partida, :composiciones_attributes, :control_attributes
  accepts_nested_attributes_for :composiciones, :reject_if => lambda { |a| a[:porcentaje].blank?}, :allow_destroy => true
  accepts_nested_attributes_for :control, :reject_if => lambda { |a| a[:valor_x].blank?}, :allow_destroy => true
  validates_presence_of :pasta_id, :fecha, :partida
end


# == Schema Information
#
# Table name: pruebas
#
#  id         :integer         not null, primary key
#  pasta_id   :integer
#  fecha      :datetime
#  partida    :string(255)
#  created_at :datetime
#  updated_at :datetime
#  horno_id   :integer
#

app/models/quemador.rb
class Quemador < ActiveRecord::Base
  belongs_to :horno
  has_many :valores
  attr_accessible :nombre, :cantidad_mecheros, :posicion
  validates_presence_of :nombre, :cantidad_mecheros, :posicion
  validates_numericality_of :cantidad_mecheros, :only_integer => true
end

# == Schema Information
#
# Table name: quemadores
#
#  id                :integer         not null, primary key
#  horno_id          :integer
#  nombre            :string(255)
#  cantidad_mecheros :string(255)
#  posicion          :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :nombre, :email, :password, :password_confirmation
  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

  def self.authenticate(nombre, password)
    user = find_by_nombre(nombre)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/models/valor.rb
class Valor < ActiveRecord::Base
  belongs_to :medicion
  belongs_to :quemador
  validates_presence_of :quemador_id, :temperatura
end

# == Schema Information
#
# Table name: valores
#
#  id          :integer         not null, primary key
#  quemador_id :integer
#  medicion_id :integer
#  temperatura :integer
#  presion     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hornos_helper.rb
module HornosHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end

  def enlaces_mediciones
    resultado = ""
    Horno.all.each do |horno|
      resultado << "<li>" + menu_item("Mediciones #{horno.codigo}", horno_mediciones_path(horno)) + "</li>"
    end
    resultado.html_safe
  end

  def menu_item(texto, ruta)
    if @tab == texto
      link_to texto, ruta, :class => "active"
    else
      link_to texto, ruta
    end
  end
end

app/helpers/mediciones_helper.rb
module MedicionesHelper
end

app/helpers/pastas_helper.rb
module PastasHelper
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/proveedores_helper.rb
module ProveedoresHelper
end

app/helpers/pruebas_helper.rb
module PruebasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application"%>
    <%= javascript_include_tag :defaults, "nested_form" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div class="main">
      <div class="header">
        <div class="header_in">
          <div class="logo">
            <h1><a href="#"><span>C</span>ontrol de laboratorio</a></h1>
          </div>
          <div class="menu_admin">
            <ul>
              <% if current_user %>
                <li><%= menu_item 'Hornos', hornos_path %></li>
                <li><%= menu_item 'Pastas', pastas_path %></li>
                <li><%= menu_item 'Productos', productos_path %></li>
                <li><%= menu_item 'Proveedores', proveedores_path %></li>
                <li><%= menu_item 'Usuarios', users_path %></li>
              <% end %>
            </ul>
          </div>
          <div class="clear"></div>
          <div class="menu_nav">
            <ul>
              <%= enlaces_mediciones %>
              <li><%= menu_item 'Pruebas', pruebas_path %></li>
            </ul>
            <div class="clear"></div>
          </div>
        </div>
      </div>
      <div class="content">
        <div class="content_in">
          <div id="container">
            <div id="user_nav">
              <% if current_user %>
                Bienvenido <%= current_user.nombre %>
              <%= link_to "Cerrar sesión", log_out_path %>
              <% else %>
                <%= link_to "Registro", registro_path %> or
                <%= link_to "Inicio de sesión", log_in_path %>
              <% end %>
            </div>
            <% flash.each do |name, msg| %>
              <%= content_tag :div, msg, :id => "flash_#{name}" %>
            <% end %>
            <%= content_tag :h1, yield(:title) if show_title? %>
            <%= yield %>
          </div>
        </div>
      </div>
      <div class="footer">
        <div class="footer_resize">
          <p class="lf">&copy; Copyright <a href="http://www.fadrell.com">Grupo fadrell</a>.</p>
          <p class="rf">Layout by Rubén <a href="#">Templates</a></p>
          <div class="clear"></div>
        </div>
      </div>
    </div>
  </body>
</html>